### ISSUE TITLE
Fix spatial metadata passed to SB so that polylines (and polygons?) are displayed

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [USGS-R/drb-temp-data-release#5]
* Right now, we are only pushing `river_metadata` to SB when building all of the xmls, since when we pass both `river_metadata` and `reservoir_metadata` only the bounding box for `reservoir_metadata` is displayed on SB:

  ![image](https://user-images.githubusercontent.com/54007288/114427494-bf262780-9b80-11eb-949e-93b6e8747766.png)

* In addition, the map displayed when we push `river_metadata` only displays the bounding box for `river_metadata`: 
  
  ![image](https://user-images.githubusercontent.com/54007288/114427327-99008780-9b80-11eb-932e-cec9a208e8c2.png)
 
  not the actual polylines, like the map in [Jordan's PGMTL data release](https://www.sciencebase.gov/catalog/item/5ebe564782ce476925e44b26):

  ![image](https://user-images.githubusercontent.com/54007288/114428357-b550f400-9b81-11eb-9e89-3094669bf92e.png)

  * This may, in part, be due to the fact that `river_metadata` is built by calling `extract_feature()` on `network_vertices_sf` rather than `modeled_network_sf`, but calling it on the latter generates the following error:
  ```
  Error in UseMethod("feature_type") : 
    no applicable method for 'feature_type' applied to an object of class "c('sfc_LINESTRING', 'sfc')"
  ```

* Finally, when we upload the zipped shapefiles:
```01_spatial_sb_shp:
    command: sb_replace_files(sbid_01_spatial,
      "out_data/01_spatial_network.zip",
      "out_data/01_reservoir_polygons.zip")
```
The data release shows them as attached files, as expected:
![image](https://user-images.githubusercontent.com/54007288/114427733-fe547880-9b80-11eb-9599-9d612d867fc4.png)

But doesn't identify that the zipped folders contain shapefiles, as is the case in [Jordan's PGMTL data release](https://www.sciencebase.gov/catalog/item/5ebe564782ce476925e44b26), which uses nearly identical commands to build and push the spatial data and metadata, though the `sf` object in that data release contains multi-polygons:
![image](https://user-images.githubusercontent.com/54007288/114427867-2217be80-9b81-11eb-85af-018445019288.png)

**Comment by jordansread** [comment]
> But doesn't identify that the zipped folders contain shapefiles, as is the case in Jordan's PGMTL data release, which uses nearly identical commands 

I had to manual convert those to spatial extensions using the SB UI to inzip and turn the contents into map services. Happy to help if that is what you want to do here. 

> Error in UseMethod("feature_type") : 
>  no applicable method for 'feature_type' applied to an object of class "c('sfc_LINESTRING', 'sfc')"
  
Please add this as an issue in [meddle](https://github.com/USGS-R/meddle/issues) it is a pretty straightforward thing to add [here-ish](https://github.com/USGS-R/meddle/blob/master/R/extract_spatial.R#L71)

**Comment by hcorson-dosch-usgs** [comment]
>I had to manual convert those to spatial extensions using the SB UI to inzip and turn the contents into map services. Happy to help if that is what you want to do here.

Thanks, @jread-usgs -- sounds like @limnoliver is fine w/ leaving as is for now, but that would be good to do when this release is finalized

**Comment by limnoliver** [comment]
This issue was fixed via updates to `meddle` and unzipping the shapefiles as Jordan indicated above. Can now see streams, reservoirs, and obs sites! https://www.sciencebase.gov/catalog/item/imap/5f6a285d82ce38aaa244912e.
